[package]
name = "definy-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
narumincho-vdom = { path = "../narumincho-vdom" }
base64 = "0.22"
ed25519-dalek = { version = "2.2" }
definy-event = { path = "../definy-event" }
web-sys = { version = "0.3.85", features = [
  "console",
  "Window",
  "Document",
  "Element",
  "Node",
  "NodeList",
  "HtmlElement",
  "Event",
  "HtmlDialogElement",
  "Navigator",
  "Clipboard",
  "Request",
  "RequestInit",
  "Response",
  "Headers",
] }
wasm-bindgen = "0.2.108"
rand = "0.8.5"
